port: 8080
pretty-logs: true
debug: false

runners:
  - name: linux_runner
    os: linux
    count: 10
    arch: x64
    self_hosted: true
  - name: mac_runner
    os: macos
    count: 2
    arch: x64
    self_hosted: true
